import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ProHunt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=js-Math+cmbx-10&display=swap"/>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Julius+Sans+One&display=swap"/>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kotta+One&display=swap"/>
    </html>
  )
}
